global using Point = System.Windows.Point;
global using Size = System.Windows.Size;
global using Color = System.Windows.Media.Color;
global using Button = System.Windows.Controls.Button;
global using ListBox = System.Windows.Controls.ListBox;
global using MouseEventArgs = System.Windows.Input.MouseEventArgs;
global using Application = System.Windows.Application;
global using Brushes = System.Windows.Media.Brushes;
global using Pen = System.Windows.Media.Pen;
global using FontFamily = System.Windows.Media.FontFamily;
global using ColorConverter = System.Windows.Media.ColorConverter;
global using Cursors = System.Windows.Input.Cursors;
global using HA = System.Windows.HorizontalAlignment;
global using FD = System.Windows.FlowDirection;
global using SO = System.Windows.Controls.Orientation;
global using System.IO;
global using System.Net.Http;
